import type { Course, CourseCategory } from './types';

export const courseCategories: CourseCategory[] = [
    { id: 'dev-pessoal', name: 'Desenvolvimento Pessoal e Profissional', imageId: 'dev-pessoal' },
    { id: 'rh-gestao', name: 'Recursos Humanos e Gestão', imageId: 'rh-gestao' },
    { id: 'minerios-petroleo', name: 'Recursos Minerais e Petróleos', imageId: 'minerios-petroleo' },
    { id: 'financas-admin', name: 'Finanças e Administração', imageId: 'financas-admin' },
    { id: 'informatica-it', name: 'Informática, IT & Software', imageId: 'informatica-it' },
    { id: 'industrial', name: 'Industrial', imageId: 'industrial' },
    { id: 'seguranca-trabalho', name: 'Higiene & Segurança no Trabalho', imageId: 'seguranca-trabalho' },
    { id: 'marketing-comercial', name: 'Gestão Comercial & Marketing', imageId: 'marketing-comercial' },
    { id: 'ingles', name: 'Curso de Inglês', imageId: 'ingles' },
];

export const courses: Course[] = [
  { id: 'TA-001', name: 'Técnicas de Apresentação', category: 'dev-pessoal' },
  { id: 'GC-002', name: 'Gestão de Conflitos', category: 'dev-pessoal' },
  { id: 'GE-003', name: 'Gestão Emocional', category: 'dev-pessoal' },
  { id: 'EA-004', name: 'Excelência no Atendimento', category: 'dev-pessoal' },
  { id: 'GR-005', name: 'Gestão de Reclamações', category: 'dev-pessoal' },
  { id: 'LMP-006', name: 'Liderança e Motivação de Pessoas', category: 'dev-pessoal' },
  { id: 'GT-008', name: 'Gestão do Tempo', category: 'dev-pessoal' },
  { id: 'CV-392', name: 'Comunicação Criativa', category: 'dev-pessoal' },
  { id: 'MI-334', name: 'Técnicas de Produtividade de Alta Performance', category: 'dev-pessoal' },

  { id: 'GERH-007', name: 'Gestão Estratégica de Recursos Humanos', category: 'rh-gestao' },
  { id: 'PU-595', name: 'Técnicas de recrutamento e selecção pessoal', category: 'rh-gestao' },
  { id: 'EP-432', name: 'Secretariado Executivo de Alta Direção', category: 'rh-gestao' },
  { id: 'ZJ-280', name: 'Desenvolvimento da Eficácia', category: 'rh-gestao' },
  { id: 'GW-14', name: 'Gestão de Equipas & Liderança', category: 'rh-gestao' },
  { id: 'EN-427', name: 'Gestão de Projectos', category: 'rh-gestao' },
  { id: 'ZH-106', name: 'Gestão Estratégica de Recursos Humanos', category: 'rh-gestao' },
  { id: 'NR-123', name: 'Formação Avançada de Gestores', category: 'rh-gestao' },
  { id: 'CM-602', name: 'Técnicas de Recrutamento e Selecção de Pessoal', category: 'rh-gestao' },
  { id: 'YM-244', name: 'Gestão de Recursos Humanos', category: 'rh-gestao' },

  { id: 'XZ-173', name: 'Gestão de recursos minerais', category: 'minerios-petroleo' },
  { id: 'YE-743', name: 'Recursos Minerais e Ambiente', category: 'minerios-petroleo' },
  { id: 'XX-168', name: 'Gestão de reservatórios de Petróleo e Gás', category: 'minerios-petroleo' },
  { id: 'NH-96', name: 'Sistema de Gestão Ambiental - ISO14001', category: 'minerios-petroleo' },
  { id: 'RA-253', name: 'Geologia para não Geólogos', category: 'minerios-petroleo' },
  { id: 'OL-341', name: 'Geofísica Nível I', category: 'minerios-petroleo' },
  { id: 'PM-599', name: 'Geofísica Nível II', category: 'minerios-petroleo' },
  { id: 'DE-510', name: 'Geofísica Nível III', category: 'minerios-petroleo' },
  { id: 'FW-403', name: 'Drilling and Well Completion', category: 'minerios-petroleo' },
  { id: 'SK-299', name: 'Gestão, Planeamento e Controlo da Produção', category: 'minerios-petroleo' },
  { id: 'QC-191', name: 'Processamento e análise de dados Sísmicos', category: 'minerios-petroleo' },
  { id: 'DS-691', name: 'Gestão do Risco em Projectos de Produção e Exploração de recursos minerais', category: 'minerios-petroleo' },
  { id: 'IC-464', name: 'Avaliação de Formações', category: 'minerios-petroleo' },
  { id: 'SI-622', name: 'Caracterização de Reservatórios', category: 'minerios-petroleo' },
  { id: 'HA-745', name: 'Fiscalidade Petrolífera Angolana', category: 'minerios-petroleo' },
  { id: 'IP-472', name: 'Geofísica de Reservatórios', category: 'minerios-petroleo' },
  { id: 'RJ-222', name: 'Geologia de campo (Técnicas de amostragem)', category: 'minerios-petroleo' },
  { id: 'HM-620', name: 'Geoquímica', category: 'minerios-petroleo' },
  { id: 'BS-556', name: 'Integrated Reservoir Management and Monitoring', category: 'minerios-petroleo' },
  { id: 'IM-626', name: 'Interpretação Sísmica', category: 'minerios-petroleo' },
  { id: 'WM-2', name: 'Bacias Angolanas', category: 'minerios-petroleo' },
  { id: 'PJ-525', name: 'Negociação e Contratos na Indústria Petrolífera', category: 'minerios-petroleo' },
  { id: 'EV-137', name: 'Geologia do Poço', category: 'minerios-petroleo' },
  { id: 'XV-126', name: 'Registo & Análise de Testemunho de Sondagem', category: 'minerios-petroleo' },
  { id: 'ML-424', name: 'Reservatórios Areníticos', category: 'minerios-petroleo' },
  { id: 'WS-674', name: 'Reservatórios Carbonáticos', category: 'minerios-petroleo' },
  { id: 'LJ-246', name: 'Corrosão Aplicada a Indústria Petrolífera', category: 'minerios-petroleo' },
  { id: 'NO-351', name: 'Produção de petróleo em Subsea', category: 'minerios-petroleo' },

  { id: 'NG-302', name: 'Finanças para não Financeiros', category: 'financas-admin' },
  { id: 'EL-229', name: 'Gestão de Tesouraria', category: 'financas-admin' },
  { id: 'FI-696', name: 'Gestão Documental e Arquivo', category: 'financas-admin' },
  { id: 'WT-424', name: 'Operações Logísticas', category: 'financas-admin' },
  { id: 'DX-267', name: 'Logística e Gestão Orçamental', category: 'financas-admin' },
  { id: 'KR-550', name: 'Gestão de Compras e Aprovisionamento', category: 'financas-admin' },
  { id: 'IE-284', name: 'Gestão de Stock', category: 'financas-admin' },
  { id: 'QE-678', name: 'Gestão de Operações', category: 'financas-admin' },
  { id: 'QA-627', name: 'Gestão de Armazéns', category: 'financas-admin' },
  { id: 'SS-526', name: 'Gestão da Cadeia de Suprimentos', category: 'financas-admin' },
  { id: 'KF-460', name: 'Gestão de Fornecedores', category: 'financas-admin' },
  { id: 'LM-471', name: 'Gestão Estratégica de Fornecedores e Outsourcing', category: 'financas-admin' },
  { id: 'XL-161', name: 'Produção e Gestão de Transportes', category: 'financas-admin' },
  { id: 'RX-63', name: 'Contabilidade do Petróleo', category: 'financas-admin' },
  { id: 'MX-32', name: 'Gestão de Tesouraria', category: 'financas-admin' },
  { id: 'RD-117', name: 'Planeamento Estratégico e Comercial', category: 'financas-admin' },
  { id: 'XL-702', name: 'Análise Financeira', category: 'financas-admin' },
  { id: 'IU-688', name: 'Contabilidade Geral', category: 'financas-admin' },
  { id: 'FI-33', name: 'Auditoria Financeira', category: 'financas-admin' },
  { id: 'HE-737', name: 'Fiscalidade', category: 'financas-admin' },
  { id: 'SG-650', name: 'Análise e Gestão Financeira de Empresas', category: 'financas-admin' },
  { id: 'ET-651', name: 'Elaboração e Análise de projectos de Investimentos', category: 'financas-admin' },
  { id: 'PJ-465', name: 'Análise de investimentos', category: 'financas-admin' },
  { id: 'EU-444', name: 'Técnicas de Elaboração de Documentos e Pareceres Técnicos', category: 'financas-admin' },
  { id: 'RE-125', name: 'Gestão Financeira', category: 'financas-admin' },
  { id: 'WZ-590', name: 'Mercado de Capitais', category: 'financas-admin' },
  { id: 'NE-466', name: 'Gestão de Riscos Financeiros', category: 'financas-admin' },
  { id: 'NW-323', name: 'Contabilidade para não Contabilistas', category: 'financas-admin' },
  { id: 'PJ-434', name: 'Gestão da Qualidade', category: 'financas-admin' },
  { id: 'HG-699', name: 'Gestão de Frotas', category: 'financas-admin' },
  { id: 'UX-668', name: 'Introdução à Gestão de Projectos para não PMs', category: 'financas-admin' },
  { id: 'IK-463', name: 'Gestão do Risco em Projectos', category: 'financas-admin' },
  { id: 'FX-528', name: 'ISO 21500 - Norma sobre Gestão de Projectos', category: 'financas-admin' },
  { id: 'FY-131', name: 'Gestão Estratégica de Projectos', category: 'financas-admin' },
  { id: 'LE-340', name: 'Planeamento e Gestão Orçamental', category: 'financas-admin' },
  { id: 'UE-320', name: 'Modelos de Previsão Financeiras', category: 'financas-admin' },
  { id: 'HM-336', name: 'Estudo de Viabilidade Económico - Financeira', category: 'financas-admin' },
  { id: 'LQ-553', name: 'Gestão da Dívida', category: 'financas-admin' },
  { id: 'RN-195', name: 'Auditoria Contabilística e Financeira', category: 'financas-admin' },
  { id: 'OG-56', name: 'Contabilidade Geral I', category: 'financas-admin' },
  { id: 'MA-306', name: 'Contabilidade Geral II', category: 'financas-admin' },
  { id: 'YY-646', name: 'Contabilidade Analítica e Orçamental', category: 'financas-admin' },
  { id: 'IX-778', name: 'Regime Fiscal Angolano', category: 'financas-admin' },
  { id: 'OI-637', name: 'Balanced Scorecard', category: 'financas-admin' },
  
  { id: 'YZ-719', name: 'SAP BASIS - Melhores Práticas de Administração de Sistemas', category: 'informatica-it' },
  { id: 'SE-447', name: 'Microsoft Powerpoint', category: 'informatica-it' },
  { id: 'MB-161', name: 'Microsoft Excel Aplicado às Compras', category: 'informatica-it' },
  { id: 'YX-341', name: 'Segurança da Informação', category: 'informatica-it' },
  { id: 'WN-613', name: 'Gestão de Projectos com o MS project', category: 'informatica-it' },
  { id: 'VF-86', name: 'Excel avançado', category: 'informatica-it' },
  { id: 'HE-749', name: 'Marketing Digital', category: 'informatica-it' },
  { id: 'JA-604', name: 'Auto Cad 3D', category: 'informatica-it' },
  { id: 'BX-274', name: 'Primavera', category: 'informatica-it' },
  { id: 'YU-738', name: 'Processamento de Salários com Primavera', category: 'informatica-it' },
  { id: 'WR-82', name: 'SAP HCM - Configuração de Processamento Salarial', category: 'informatica-it' },
  { id: 'ZW-61', name: 'Excel Intermédio', category: 'informatica-it' },
  { id: 'JS-779', name: 'Excel Avançado', category: 'informatica-it' },
  { id: 'WH-155', name: 'Excel Básico', category: 'informatica-it' },
  { id: 'YF-360', name: 'SAP BASIS - Melhores Práticas de Administração de Sistemas', category: 'informatica-it' },
  { id: 'NE-74', name: 'Power BI Microsoft', category: 'informatica-it' },
  { id: 'BT-436', name: 'Administração de Redes e Infraestruturas', category: 'informatica-it' },
  { id: 'PN-781', name: 'Segurança Informática (Sistemas e Informação)', category: 'informatica-it' },
  { id: 'KE-540', name: 'Microsoft Word', category: 'informatica-it' },
  { id: 'TY-158', name: 'Microsoft Outlook', category: 'informatica-it' },
  { id: 'WI-132', name: 'Microsoft Access', category: 'informatica-it' },
  { id: 'LT-654', name: 'Microsoft Teams', category: 'informatica-it' },
  { id: 'CZ-730', name: 'Microsoft Office', category: 'informatica-it' },
  { id: 'TF-83', name: 'Primavera', category: 'informatica-it' },
  { id: 'IW-791', name: 'SAP-Aplicação IPL (módulo 1)', category: 'informatica-it' },
  { id: 'TQ-229', name: 'SAP-Aplicação IPL (módulo 2)', category: 'informatica-it' },
  { id: 'IP-304', name: 'Hardware', category: 'informatica-it' },
  { id: 'BA-621', name: 'Redes e Comunicações Estruturadas', category: 'informatica-it' },
  { id: 'AE-78', name: 'Segurança Informática', category: 'informatica-it' },
  { id: 'MA-290', name: 'Excel para Finanças', category: 'informatica-it' },

  { id: 'ZQ-337', name: 'Alinhamento de Bombas', category: 'industrial' },
  { id: 'JM-665', name: 'Inspecção e Calibração de equipamentos', category: 'industrial' },
  { id: 'OB-60', name: 'Manutenção e Reparação de Válvulas', category: 'industrial' },
  { id: 'EQ-477', name: 'Inspecção de Equipamentos', category: 'industrial' },
  { id: 'IT-121', name: 'Revestimento de Tubulações', category: 'industrial' },
  { id: 'YL-705', name: 'ROV-Remotely Operated Vehicle', category: 'industrial' },
  { id: 'BH-705', name: 'Montagem e Inspecção De Andaimes', category: 'industrial' },
  { id: 'YG-545', name: 'Operador De Empilhadora Pettibone', category: 'industrial' },
  { id: 'QE-471', name: 'Instrumentação Industrial', category: 'industrial' },
  { id: 'XD-764', name: 'Soldadura Industrial', category: 'industrial' },
  { id: 'FV-577', name: 'Pintura Industrial', category: 'industrial' },
  { id: 'GS-392', name: 'Instrumentação e Controle de Processos', category: 'industrial' },
  { id: 'GD-306', name: 'Automação Industrial', category: 'industrial' },
  { id: 'UB-322', name: 'Operador de Produção', category: 'industrial' },
  { id: 'LV-253', name: 'Operador de Sala de Controlo', category: 'industrial' },
  { id: 'LR-505', name: 'PLC - Controladores Lógicos Programáveis', category: 'industrial' },
  { id: 'MU-18', name: 'Manutenção Industrial', category: 'industrial' },
  { id: 'IJ-222', name: 'Gestão da Qualidade', category: 'industrial' },
  { id: 'TG-1', name: 'Segurança Elétrica Industrial', category: 'industrial' },
  { id: 'ER-426', name: 'Segurança de Processos Industriais', category: 'industrial' },
  { id: 'KF-580', name: 'Manutenção e Reparação de Válvulas', category: 'industrial' },
  { id: 'LF-556', name: 'Gestão e Controle da Manutenção Industrial', category: 'industrial' },
  { id: 'ER-534', name: 'Gestão por Processos e Indicadores Desempenho', category: 'industrial' },
  { id: 'YW-773', name: 'Gestão de Resíduos Industriais - Introdução', category: 'industrial' },
  { id: 'AI-522', name: 'Gestão de Projectos Industriais', category: 'industrial' },
  { id: 'EH-537', name: 'Gestão da Manutenção de Máquinas e Equipamentos', category: 'industrial' },

  { id: 'GR-610', name: 'Higiene e Segurança no Trabalho', category: 'seguranca-trabalho' },
  { id: 'XX-136', name: 'Segurança Industrial e Prevenção de Riscos', category: 'seguranca-trabalho' },
  { id: 'CF-669', name: 'Segurança de Máquinas – ISO 13857', category: 'seguranca-trabalho' },
  
  { id: 'FU-581', name: 'Técnicas de Vendas', category: 'marketing-comercial' },
  { id: 'YR-504', name: 'Gestão Comercial', category: 'marketing-comercial' },
  { id: 'VH-377', name: 'Gestão de Clientes', category: 'marketing-comercial' },
  { id: 'RT-97', name: 'Gestão de Cobranças', category: 'marketing-comercial' },
  { id: 'FG-179', name: 'Técnicas de Venda', category: 'marketing-comercial' },
  { id: 'JF-104', name: 'Técnicas de Negociação', category: 'marketing-comercial' },
  { id: 'VP-601', name: 'Gestão da Cadeia de Suprimentos', category: 'marketing-comercial' },
  { id: 'UX-630', name: 'Gestão de Fornecedores', category: 'marketing-comercial' },
  { id: 'BP-642', name: 'Gestão das Reclamações', category: 'marketing-comercial' },
  { id: 'DH-572', name: 'Gestão de Marketing', category: 'marketing-comercial' },
  { id: 'TI-143', name: 'Marketing Digital', category: 'marketing-comercial' },
  { id: 'ZY-424', name: 'ROI Marketing', category: 'marketing-comercial' },
  { id: 'YL-38', name: 'Gestão Comercial', category: 'marketing-comercial' },
  { id: 'NF-265', name: 'Gestão de Clientes', category: 'marketing-comercial' },
  { id: 'RD-181', name: 'Gestão de Cobranças', category: 'marketing-comercial' },
  { id: 'FS-367', name: 'Técnicas de Venda', category: 'marketing-comercial' },
  { id: 'TJ-15', name: 'Técnicas de Negociação', category: 'marketing-comercial' },
  { id: 'ND-408', name: 'Gestão da Cadeia de Suprimentos', category: 'marketing-comercial' },
  { id: 'QW-537', name: 'Gestão de Fornecedores', category: 'marketing-comercial' },
  
  { id: 'YA-332', name: 'Beginner', category: 'ingles' },
  { id: 'NX-537', name: 'Elementary', category: 'ingles' },
  { id: 'ZY-640', name: 'Pre-Intermediate', category: 'ingles' },
  { id: 'RX-125', name: 'Intermediate', category: 'ingles' },
  { id: 'JF-778', name: 'Upper Intermediate', category: 'ingles' },
  { id: 'WY-697', name: 'Advanced', category: 'ingles' },
];
