import type { Course, CourseCategory } from './types';

export const courseCategories: CourseCategory[] = [
    { id: 'dev-pessoal', name: 'Desenvolvimento Pessoal e Profissional' },
    { id: 'rh-gestao', name: 'Recursos Humanos e Gestão' },
    { id: 'minerios-petroleo', name: 'Recursos Minerais e Petróleos' },
    { id: 'financas-admin', name: 'Finanças e Administração' },
    { id: 'informatica-it', name: 'Informática, IT & Software' },
    { id: 'industrial', name: 'Industrial' },
    { id: 'seguranca-trabalho', name: 'Higiene & Segurança no Trabalho' },
    { id: 'marketing-comercial', name: 'Gestão Comercial & Marketing' },
    { id: 'ingles', name: 'Curso de Inglês' },
];

export const courses: Course[] = [
  { 
    id: 'TA-001', 
    name: 'Técnicas de Apresentação', 
    category: 'dev-pessoal', 
    imageId: 'course-presentation',
    duration: '24 horas',
    generalObjective: 'Desenvolver as competências de comunicação e apresentação em público, permitindo realizar apresentações eficazes e de alto impacto.',
    whatYouWillLearn: [
      'Estruturar uma apresentação de forma lógica e cativante.',
      'Utilizar a comunicação verbal e não-verbal de forma eficaz.',
      'Gerir o nervosismo e a ansiedade ao falar em público.',
      'Criar suportes visuais (slides) claros e apelativos.',
      'Adaptar a apresentação a diferentes tipos de audiência.'
    ],
    modules: [
      { title: 'Módulo 1: Planeamento e Estrutura da Apresentação', topics: ['Definição de objetivos', 'Análise da audiência', 'Estruturas de discurso (Storytelling)', 'Organização do conteúdo'] },
      { title: 'Módulo 2: Comunicação e Expressão', topics: ['Linguagem verbal: clareza, tom e ritmo', 'Linguagem não-verbal: postura, gestos e contacto visual', 'Técnicas de dicção e projecção de voz'] },
      { title: 'Módulo 3: O Apresentador', topics: ['Gestão da ansiedade e autoconfiança', 'Interação com a audiência', 'Gestão de perguntas e respostas'] },
      { title: 'Módulo 4: Suportes Visuais', topics: ['Design de slides (PowerPoint/Google Slides)', 'Princípios de design gráfico para apresentações', 'Uso de imagens, gráficos e multimédia'] }
    ]
  },
  { 
    id: 'GC-002', 
    name: 'Gestão de Conflitos', 
    category: 'dev-pessoal', 
    imageId: 'course-conflict',
    duration: '20 horas',
    generalObjective: 'Capacitar os participantes com ferramentas e técnicas para identificar, gerir e resolver conflitos de forma construtiva no ambiente de trabalho.',
    whatYouWillLearn: [
      'Compreender a natureza e as causas dos conflitos.',
      'Identificar os diferentes estilos de gestão de conflitos.',
      'Aplicar técnicas de negociação e mediação.',
      'Desenvolver a comunicação assertiva para prevenção de conflitos.',
      'Transformar situações de conflito em oportunidades de crescimento.'
    ],
    modules: [
      { title: 'Módulo 1: Introdução ao Conflito', topics: ['Tipos e níveis de conflito', 'Causas comuns de conflitos nas organizações', 'O ciclo de vida do conflito'] },
      { title: 'Módulo 2: Estilos de Gestão de Conflitos', topics: ['Diagnóstico de estilos pessoais', 'Vantagens e desvantagens de cada estilo (evitamento, acomodação, competição, colaboração, compromisso)'] },
      { title: 'Módulo 3: Comunicação e Negociação', topics: ['Escuta ativa e empatia', 'Comunicação assertiva vs. agressiva/passiva', 'Princípios da negociação de Harvard'] },
      { title: 'Módulo 4: Mediação e Resolução', topics: ['O papel do mediador', 'Passos para a resolução de conflitos', 'Criação de acordos ganha-ganha'] }
    ]
  },
  { id: 'LMP-006', name: 'Liderança e Motivação de Pessoas', category: 'dev-pessoal', imageId: 'course-leadership', duration: '30 horas', generalObjective: 'Capacitar os participantes com as competências essenciais para liderar e motivar equipas, promovendo um ambiente de trabalho produtivo e positivo.', whatYouWillLearn: ['Compreender os diferentes estilos de liderança e quando aplicá-los.', 'Desenvolver a inteligência emocional para liderar com empatia.', 'Aprender técnicas eficazes de comunicação e feedback.', 'Aplicar estratégias de motivação e reconhecimento.', 'Gerir o desempenho da equipa e promover o desenvolvimento individual.'], modules: [{ title: 'Módulo 1: Fundamentos da Liderança', topics: ['Teorias de liderança', 'Líder vs. Chefe', 'O papel do líder no século XXI'] }, { title: 'Módulo 2: Inteligência Emocional na Liderança', topics: ['Autoconhecimento e autogestão', 'Empatia e gestão de relacionamentos', 'Tomada de decisão emocionalmente inteligente'] }, { title: 'Módulo 3: Comunicação e Feedback', topics: ['Comunicação assertiva', 'Técnicas de feedback construtivo', 'Condução de reuniões eficazes'] }, { title: 'Módulo 4: Motivação e Gestão de Desempenho', topics: ['Teorias da motivação (Maslow, Herzberg)', 'Estratégias de reconhecimento e recompensa', 'Definição de metas SMART e avaliação de desempenho'] }] },
  { id: 'EN-427', name: 'Gestão de Projectos', category: 'rh-gestao', imageId: 'course-project-management', duration: '40 horas', generalObjective: 'Fornecer aos participantes os conhecimentos, ferramentas e técnicas fundamentais para gerir projectos de forma eficaz, desde o início até à conclusão.', whatYouWillLearn: ['Compreender o ciclo de vida de um projecto.', 'Definir o escopo, cronograma, custos e qualidade do projecto.', 'Identificar e gerir riscos.', 'Gerir a comunicação e as partes interessadas (stakeholders).', 'Utilizar metodologias de gestão de projectos (PMBOK, Agile).'], modules: [{ title: 'Módulo 1: Introdução à Gestão de Projectos', topics: ['O que é um projecto?', 'O papel do Gestor de Projectos', 'Estruturas organizacionais e projectos'] }, { title: 'Módulo 2: Iniciação e Planeamento do Projecto', topics: ['Elaboração do Project Charter', 'Definição do escopo (WBS)', 'Criação do cronograma e orçamento'] }, { title: 'Módulo 3: Execução, Monitorização e Controlo', topics: ['Gestão da equipa do projecto', 'Monitorização do progresso (KPIs)', 'Gestão de mudanças e riscos'] }, { title: 'Módulo 4: Encerramento do Projecto e Metodologias', topics: ['Entrega do projecto', 'Lições aprendidas', 'Introdução ao Scrum e Kanban'] }] },
  { id: 'NE-74', name: 'Power BI Microsoft', category: 'informatica-it', imageId: 'course-power-bi', duration: '35 horas', generalObjective: 'Capacitar os participantes a transformar dados brutos em dashboards e relatórios interactivos e visualmente apelativos, utilizando o Microsoft Power BI.', whatYouWillLearn: ['Conectar e transformar dados de diversas fontes (Excel, SQL, etc.).', 'Modelar dados para criar relações e hierarquias.', 'Criar visualizações de dados (gráficos, tabelas, mapas).', 'Utilizar a linguagem DAX para criar medidas e colunas calculadas.', 'Publicar e partilhar relatórios no serviço Power BI.'], modules: [{ title: 'Módulo 1: Introdução ao Power BI', topics: ['O que é o Power BI (Desktop, Service, Mobile)', 'Instalação e interface', 'Fluxo de trabalho no Power BI'] }, { title: 'Módulo 2: Obter e Transformar Dados (Power Query)', topics: ['Conectar a diferentes fontes de dados', 'Limpeza e transformação de dados', 'Fusão e anexação de consultas'] }, { title: 'Módulo 3: Modelação de Dados e DAX', topics: ['Criação de relacionamentos', 'Criação de colunas calculadas e medidas', 'Introdução às funções DAX mais comuns'] }, { title: 'Módulo 4: Visualização e Publicação', topics: ['Criação de relatórios e dashboards', 'Formatação e personalização de visuais', 'Publicação no Power BI Service e partilha'] }] },
  { id: 'GC-003', name: 'Gestão Emocional', category: 'dev-pessoal', imageId: 'course-emotional', duration: '16 horas', generalObjective: 'Desenvolver a inteligência emocional dos participantes para melhorarem o autoconhecimento, a autogestão, a empatia e os relacionamentos interpessoais.', whatYouWillLearn: ['Reconhecer e compreender as próprias emoções.', 'Gerir emoções e impulsos de forma saudável.', 'Desenvolver a empatia para compreender os outros.', 'Construir relacionamentos mais fortes e positivos.', 'Aplicar a inteligência emocional na resolução de problemas.'], modules: [{ title: 'Módulo 1: Os Pilares da Inteligência Emocional', topics: ['Definição e importância', 'Autoconsciência emocional'] }, { title: 'Módulo 2: Autogestão', topics: ['Controlo de impulsos', 'Gestão do stress', 'Automotivação'] }, { title: 'Módulo 3: Consciência Social', topics: ['Empatia', 'Consciência organizacional'] }, { title: 'Módulo 4: Gestão de Relacionamentos', topics: ['Comunicação eficaz', 'Influência e liderança', 'Trabalho em equipa'] }] },
  { id: 'EA-004', name: 'Excelência no Atendimento', category: 'dev-pessoal', imageId: 'course-service', duration: '20 horas', generalObjective: 'Capacitar os profissionais com as técnicas e atitudes necessárias para prestar um atendimento ao cliente de excelência, fidelizando clientes e fortalecendo a marca.', whatYouWillLearn: ['Compreender as expectativas do cliente moderno.', 'Desenvolver competências de comunicação e escuta ativa.', 'Lidar com clientes difíceis e situações de reclamação.', 'Personalizar o atendimento e criar experiências memoráveis.', 'Utilizar o feedback do cliente para a melhoria contínua.'], modules: [{ title: 'Módulo 1: O Cliente no Centro', topics: ['Jornada do cliente', 'Momentos da verdade', 'Criação de valor para o cliente'] }, { title: 'Módulo 2: Comunicação Efetiva', topics: ['Comunicação verbal e não-verbal', 'Técnicas de questionamento', 'Empatia no atendimento'] }, { title: 'Módulo 3: Gestão de Reclamações', topics: ['Oportunidades nas reclamações', 'Passos para resolver uma reclamação', 'Técnicas de "descompressão"'] }, { title: 'Módulo 4: Fidelização e Encantamento', topics: ['Ir além das expectativas', 'Técnicas de personalização', 'O papel do pós-venda'] }] },
  { id: 'GR-005', name: 'Gestão de Reclamações', category: 'dev-pessoal', imageId: 'course-complaint', duration: '16 horas', generalObjective: 'Dotar os participantes das competências necessárias para gerir reclamações de forma eficaz, transformando clientes insatisfeitos em clientes leais.', whatYouWillLearn: ['Entender a importância de uma boa gestão de reclamações.', 'Aplicar um processo estruturado para o tratamento de reclamações.', 'Desenvolver a capacidade de escuta ativa e empatia.', 'Comunicar de forma clara e assertiva em situações de tensão.', 'Utilizar as reclamações como fonte de melhoria para a organização.'], modules: [{ title: 'Módulo 1: A Reclamação como Oportunidade', topics: ['Por que os clientes reclamam (e por que não reclamam)', 'Impacto de uma má gestão de reclamações', 'O valor do cliente que reclama'] }, { title: 'Módulo 2: Processo de Gestão de Reclamações', topics: ['Acolhimento e registo', 'Análise e investigação', 'Resolução e compensação', 'Comunicação e fecho'] }, { title: 'Módulo 3: Competências Comportamentais', topics: ['Inteligência emocional na gestão de reclamações', 'Técnicas de comunicação assertiva', 'Como lidar com a agressividade'] }, { title: 'Módulo 4: Prevenção e Melhoria Contínua', topics: ['Análise da causa raiz das reclamações', 'Implementação de ações corretivas e preventivas', 'Criação de uma cultura focada no cliente'] }] },
  { id: 'GT-008', name: 'Gestão do Tempo', category: 'dev-pessoal', imageId: 'course-time', duration: '12 horas', generalObjective: 'Ajudar os participantes a otimizar o uso do seu tempo, aumentando a produtividade pessoal e profissional e reduzindo o stress.', whatYouWillLearn: ['Identificar os principais "ladrões de tempo".', 'Aprender a definir prioridades e a planear tarefas.', 'Aplicar ferramentas e técnicas de organização (Matriz de Eisenhower, Pomodoro).', 'Gerir interrupções e aprender a dizer "não".', 'Criar um sistema de gestão do tempo pessoal e sustentável.'], modules: [{ title: 'Módulo 1: Diagnóstico e Consciencialização', topics: ['Registo e análise do uso do tempo', 'Identificação de maus hábitos e "desperdiçadores" de tempo'] }, { title: 'Módulo 2: Planeamento e Priorização', topics: ['Definição de metas e objetivos', 'Matriz de Eisenhower (Urgente vs. Importante)', 'Planeamento diário e semanal'] }, { title: 'Módulo 3: Ferramentas e Técnicas', topics: ['Técnica Pomodoro', 'Método GTD (Getting Things Done)', 'Uso de agendas e ferramentas digitais'] }, { title: 'Módulo 4: Foco e Disciplina', topics: ['Gestão de interrupções e distrações', 'A arte de delegar', 'Equilíbrio entre vida profissional e pessoal'] }] },
  { id: 'CV-392', name: 'Comunicação Criativa', category: 'dev-pessoal', imageId: 'course-creative', duration: '18 horas', generalObjective: 'Estimular a criatividade na comunicação, permitindo aos participantes gerar ideias inovadoras e comunicá-las de forma impactante e memorável.', whatYouWillLearn: ['Desbloquear o pensamento criativo.', 'Aplicar técnicas de brainstorming e ideação.', 'Estruturar narrativas envolventes (storytelling).', 'Utilizar o humor e a emoção na comunicação.', 'Adaptar a comunicação criativa a diferentes meios (digital, presencial).'], modules: [{ title: 'Módulo 1: O Que é a Criatividade?', topics: ['Mitos sobre a criatividade', 'O processo criativo', 'Técnicas para estimular a criatividade'] }, { title: 'Módulo 2: Ferramentas de Ideação', topics: ['Brainstorming e Brainwriting', 'Mapas Mentais', 'Técnica SCAMPER'] }, { title: 'Módulo 3: Storytelling para Negócios', topics: ['A jornada do herói aplicada a marcas e produtos', 'Construção de personagens e enredo', 'Como usar histórias para vender ideias'] }, { title: 'Módulo 4: Comunicação de Alto Impacto', topics: ['O poder da metáfora e da analogia', 'Uso do humor e da surpresa', 'Design de apresentações criativas'] }] },
  { id: 'MI-334', name: 'Técnicas de Produtividade de Alta Performance', category: 'dev-pessoal', imageId: 'course-performance', duration: '24 horas', generalObjective: 'Equipar os participantes com um arsenal de técnicas e hábitos para alcançar a alta performance, maximizando a produtividade e o bem-estar.', whatYouWillLearn: ['Compreender os princípios da alta performance.', 'Desenvolver o foco profundo (Deep Work).', 'Otimizar a energia física e mental.', 'Construir hábitos de sucesso.', 'Utilizar a tecnologia a favor da produtividade.'], modules: [{ title: 'Módulo 1: A Mentalidade da Alta Performance', topics: ['Clareza de objetivos', 'Psicologia do flow', 'Mindset de crescimento'] }, { title: 'Módulo 2: Gestão do Foco e Energia', topics: ['Técnicas de Deep Work', 'Gestão de ciclos de energia (Ultradian Rhythms)', 'A importância do descanso e da recuperação'] }, { title: 'Módulo 3: Hábitos e Rotinas', topics: ['O poder dos hábitos (O Loop do Hábito)', 'Construção de rotinas matinais e noturnas', 'Técnica do "Habit Stacking"'] }, { title: 'Módulo 4: Ferramentas e Sistemas', topics: ['Método Zettelkasten para gestão do conhecimento', 'Automação de tarefas repetitivas', 'Configuração de um ambiente de trabalho produtivo'] }] },
];
