import type { Course, CourseCategory } from './types';

export const courseCategories: CourseCategory[] = [
    { id: 'dev-pessoal', name: 'Desenvolvimento Pessoal e Profissional' },
    { id: 'rh-gestao', name: 'Recursos Humanos e Gestão' },
    { id: 'minerios-petroleo', name: 'Recursos Minerais e Petróleos' },
    { id: 'financas-admin', name: 'Finanças e Administração' },
    { id: 'informatica-it', name: 'Informática, IT & Software' },
    { id: 'industrial', name: 'Industrial' },
    { id: 'seguranca-trabalho', name: 'Higiene & Segurança no Trabalho' },
    { id: 'marketing-comercial', name: 'Gestão Comercial & Marketing' },
    { id: 'ingles', name: 'Curso de Inglês' },
];

export const courses: Course[] = [
  { id: 'TA-001', name: 'Técnicas de Apresentação', category: 'dev-pessoal', imageId: 'course-presentation' },
  { id: 'GC-002', name: 'Gestão de Conflitos', category: 'dev-pessoal', imageId: 'course-conflict' },
  { id: 'GE-003', name: 'Gestão Emocional', category: 'dev-pessoal', imageId: 'course-emotional' },
  { id: 'EA-004', name: 'Excelência no Atendimento', category: 'dev-pessoal', imageId: 'course-service' },
  { id: 'GR-005', name: 'Gestão de Reclamações', category: 'dev-pessoal', imageId: 'course-complaint' },
  { id: 'LMP-006', name: 'Liderança e Motivação de Pessoas', category: 'dev-pessoal', imageId: 'course-leadership' },
  { id: 'GT-008', name: 'Gestão do Tempo', category: 'dev-pessoal', imageId: 'course-time' },
  { id: 'CV-392', name: 'Comunicação Criativa', category: 'dev-pessoal', imageId: 'course-creative' },
  { id: 'MI-334', name: 'Técnicas de Produtividade de Alta Performance', category: 'dev-pessoal', imageId: 'course-performance' },

  { id: 'GERH-007', name: 'Gestão Estratégica de Recursos Humanos', category: 'rh-gestao', imageId: 'course-strategic-hr' },
  { id: 'PU-595', name: 'Técnicas de recrutamento e selecção pessoal', category: 'rh-gestao', imageId: 'course-recruitment' },
  { id: 'EP-432', name: 'Secretariado Executivo de Alta Direção', category: 'rh-gestao', imageId: 'course-executive' },
  { id: 'ZJ-280', name: 'Desenvolvimento da Eficácia', category: 'rh-gestao', imageId: 'course-effectiveness' },
  { id: 'GW-14', name: 'Gestão de Equipas & Liderança', category: 'rh-gestao', imageId: 'course-team-management' },
  { id: 'EN-427', name: 'Gestão de Projectos', category: 'rh-gestao', imageId: 'course-project-management' },
  { id: 'ZH-106', name: 'Gestão Estratégica de Recursos Humanos', category: 'rh-gestao', imageId: 'course-strategic-hr-2' },
  { id: 'NR-123', name: 'Formação Avançada de Gestores', category: 'rh-gestao', imageId: 'course-advanced-managers' },
  { id: 'CM-602', name: 'Técnicas de Recrutamento e Selecção de Pessoal', category: 'rh-gestao', imageId: 'course-recruitment-2' },
  { id: 'YM-244', name: 'Gestão de Recursos Humanos', category: 'rh-gestao', imageId: 'course-hr-management' },

  { id: 'XZ-173', name: 'Gestão de recursos minerais', category: 'minerios-petroleo', imageId: 'course-minerals' },
  { id: 'YE-743', name: 'Recursos Minerais e Ambiente', category: 'minerios-petroleo', imageId: 'course-minerals-env' },
  { id: 'XX-168', name: 'Gestão de reservatórios de Petróleo e Gás', category: 'minerios-petroleo', imageId: 'course-oil-gas' },
  { id: 'NH-96', name: 'Sistema de Gestão Ambiental - ISO14001', category: 'minerios-petroleo', imageId: 'course-iso14001' },
  { id: 'RA-253', name: 'Geologia para não Geólogos', category: 'minerios-petroleo', imageId: 'course-geology' },
  { id: 'OL-341', name: 'Geofísica Nível I', category: 'minerios-petroleo', imageId: 'course-geophysics-1' },
  { id: 'PM-599', name: 'Geofísica Nível II', category: 'minerios-petroleo', imageId: 'course-geophysics-2' },
  { id: 'DE-510', name: 'Geofísica Nível III', category: 'minerios-petroleo', imageId: 'course-geophysics-3' },
  { id: 'FW-403', name: 'Drilling and Well Completion', category: 'minerios-petroleo', imageId: 'course-drilling' },
  { id: 'SK-299', name: 'Gestão, Planeamento e Controlo da Produção', category: 'minerios-petroleo', imageId: 'course-production-control' },
  { id: 'QC-191', name: 'Processamento e análise de dados Sísmicos', category: 'minerios-petroleo', imageId: 'course-seismic' },
  { id: 'DS-691', name: 'Gestão do Risco em Projectos de Produção e Exploração de recursos minerais', category: 'minerios-petroleo', imageId: 'course-risk-mining' },
  { id: 'IC-464', name: 'Avaliação de Formações', category: 'minerios-petroleo', imageId: 'course-formation-eval' },
  { id: 'SI-622', name: 'Caracterização de Reservatórios', category: 'minerios-petroleo', imageId: 'course-reservoir' },
  { id: 'HA-745', name: 'Fiscalidade Petrolífera Angolana', category: 'minerios-petroleo', imageId: 'course-angola-oil-tax' },
  { id: 'IP-472', name: 'Geofísica de Reservatórios', category: 'minerios-petroleo', imageId: 'course-reservoir-geophysics' },
  { id: 'RJ-222', name: 'Geologia de campo (Técnicas de amostragem)', category: 'minerios-petroleo', imageId: 'course-field-geology' },
  { id: 'HM-620', name: 'Geoquímica', category: 'minerios-petroleo', imageId: 'course-geochemistry' },
  { id: 'BS-556', name: 'Integrated Reservoir Management and Monitoring', category: 'minerios-petroleo', imageId: 'course-irm' },
  { id: 'IM-626', name: 'Interpretação Sísmica', category: 'minerios-petroleo', imageId: 'course-seismic-interpretation' },
  { id: 'WM-2', name: 'Bacias Angolanas', category: 'minerios-petroleo', imageId: 'course-angola-basins' },
  { id: 'PJ-525', name: 'Negociação e Contratos na Indústria Petrolífera', category: 'minerios-petroleo', imageId: 'course-oil-contracts' },
  { id: 'EV-137', name: 'Geologia do Poço', category: 'minerios-petroleo', imageId: 'course-well-geology' },
  { id: 'XV-126', name: 'Registo & Análise de Testemunho de Sondagem', category: 'minerios-petroleo', imageId: 'course-core-analysis' },
  { id: 'ML-424', name: 'Reservatórios Areníticos', category: 'minerios-petroleo', imageId: 'course-sandstone' },
  { id: 'WS-674', name: 'Reservatórios Carbonáticos', category: 'minerios-petroleo', imageId: 'course-carbonate' },
  { id: 'LJ-246', name: 'Corrosão Aplicada a Indústria Petrolífera', category: 'minerios-petroleo', imageId: 'course-corrosion' },
  { id: 'NO-351', name: 'Produção de petróleo em Subsea', category: 'minerios-petroleo', imageId: 'course-subsea' },

  { id: 'NG-302', name: 'Finanças para não Financeiros', category: 'financas-admin', imageId: 'course-finance-non-finance' },
  { id: 'EL-229', name: 'Gestão de Tesouraria', category: 'financas-admin', imageId: 'course-treasury' },
  { id: 'FI-696', name: 'Gestão Documental e Arquivo', category: 'financas-admin', imageId: 'course-document-management' },
  { id: 'WT-424', name: 'Operações Logísticas', category: 'financas-admin', imageId: 'course-logistics' },
  { id: 'DX-267', name: 'Logística e Gestão Orçamental', category: 'financas-admin', imageId: 'course-logistics-budget' },
  { id: 'KR-550', name: 'Gestão de Compras e Aprovisionamento', category: 'financas-admin', imageId: 'course-procurement' },
  { id: 'IE-284', name: 'Gestão de Stock', category: 'financas-admin', imageId: 'course-stock' },
  { id: 'QE-678', name: 'Gestão de Operações', category: 'financas-admin', imageId: 'course-operations' },
  { id: 'QA-627', name: 'Gestão de Armazéns', category: 'financas-admin', imageId: 'course-warehouse' },
  { id: 'SS-526', name: 'Gestão da Cadeia de Suprimentos', category: 'financas-admin', imageId: 'course-supply-chain' },
  { id: 'KF-460', name: 'Gestão de Fornecedores', category: 'financas-admin', imageId: 'course-supplier' },
  { id: 'LM-471', name: 'Gestão Estratégica de Fornecedores e Outsourcing', category: 'financas-admin', imageId: 'course-strategic-sourcing' },
  { id: 'XL-161', name: 'Produção e Gestão de Transportes', category: 'financas-admin', imageId: 'course-transport' },
  { id: 'RX-63', name: 'Contabilidade do Petróleo', category: 'financas-admin', imageId: 'course-oil-accounting' },
  { id: 'MX-32', name: 'Gestão de Tesouraria', category: 'financas-admin', imageId: 'course-treasury-2' },
  { id: 'RD-117', name: 'Planeamento Estratégico e Comercial', category: 'financas-admin', imageId: 'course-strategic-planning' },
  { id: 'XL-702', name: 'Análise Financeira', category: 'financas-admin', imageId: 'course-financial-analysis' },
  { id: 'IU-688', name: 'Contabilidade Geral', category: 'financas-admin', imageId: 'course-general-accounting' },
  { id: 'FI-33', name: 'Auditoria Financeira', category: 'financas-admin', imageId: 'course-financial-audit' },
  { id: 'HE-737', name: 'Fiscalidade', category: 'financas-admin', imageId: 'course-taxation' },
  { id: 'SG-650', name: 'Análise e Gestão Financeira de Empresas', category: 'financas-admin', imageId: 'course-corp-finance' },
  { id: 'ET-651', name: 'Elaboração e Análise de projectos de Investimentos', category: 'financas-admin', imageId: 'course-investment-projects' },
  { id: 'PJ-465', name: 'Análise de investimentos', category: 'financas-admin', imageId: 'course-investment-analysis' },
  { id: 'EU-444', name: 'Técnicas de Elaboração de Documentos e Pareceres Técnicos', category: 'financas-admin', imageId: 'course-technical-writing' },
  { id: 'RE-125', name: 'Gestão Financeira', category: 'financas-admin', imageId: 'course-financial-management' },
  { id: 'WZ-590', name: 'Mercado de Capitais', category: 'financas-admin', imageId: 'course-capital-markets' },
  { id: 'NE-466', name: 'Gestão de Riscos Financeiros', category: 'financas-admin', imageId: 'course-financial-risk' },
  { id: 'NW-323', name: 'Contabilidade para não Contabilistas', category: 'financas-admin', imageId: 'course-accounting-non-accountants' },
  { id: 'PJ-434', name: 'Gestão da Qualidade', category: 'financas-admin', imageId: 'course-quality-management' },
  { id: 'HG-699', name: 'Gestão de Frotas', category: 'financas-admin', imageId: 'course-fleet-management' },
  { id: 'UX-668', name: 'Introdução à Gestão de Projectos para não PMs', category: 'financas-admin', imageId: 'course-intro-pm' },
  { id: 'IK-463', name: 'Gestão do Risco em Projectos', category: 'financas-admin', imageId: 'course-project-risk' },
  { id: 'FX-528', name: 'ISO 21500 - Norma sobre Gestão de Projectos', category: 'financas-admin', imageId: 'course-iso21500' },
  { id: 'FY-131', name: 'Gestão Estratégica de Projectos', category: 'financas-admin', imageId: 'course-strategic-pm' },
  { id: 'LE-340', name: 'Planeamento e Gestão Orçamental', category: 'financas-admin', imageId: 'course-budgeting' },
  { id: 'UE-320', name: 'Modelos de Previsão Financeiras', category: 'financas-admin', imageId: 'course-financial-modeling' },
  { id: 'HM-336', name: 'Estudo de Viabilidade Económico - Financeira', category: 'financas-admin', imageId: 'course-feasibility-study' },
  { id: 'LQ-553', name: 'Gestão da Dívida', category: 'financas-admin', imageId: 'course-debt-management' },
  { id: 'RN-195', name: 'Auditoria Contabilística e Financeira', category: 'financas-admin', imageId: 'course-accounting-audit' },
  { id: 'OG-56', name: 'Contabilidade Geral I', category: 'financas-admin', imageId: 'course-gen-accounting-1' },
  { id: 'MA-306', name: 'Contabilidade Geral II', category: 'financas-admin', imageId: 'course-gen-accounting-2' },
  { id: 'YY-646', name: 'Contabilidade Analítica e Orçamental', category: 'financas-admin', imageId: 'course-analytical-accounting' },
  { id: 'IX-778', name: 'Regime Fiscal Angolano', category: 'financas-admin', imageId: 'course-angola-tax' },
  { id: 'OI-637', name: 'Balanced Scorecard', category: 'financas-admin', imageId: 'course-bsc' },
  
  { id: 'YZ-719', name: 'SAP BASIS - Melhores Práticas de Administração de Sistemas', category: 'informatica-it', imageId: 'course-sap-basis' },
  { id: 'SE-447', name: 'Microsoft Powerpoint', category: 'informatica-it', imageId: 'course-powerpoint' },
  { id: 'MB-161', name: 'Microsoft Excel Aplicado às Compras', category: 'informatica-it', imageId: 'course-excel-purchasing' },
  { id: 'YX-341', name: 'Segurança da Informação', category: 'informatica-it', imageId: 'course-infosec' },
  { id: 'WN-613', name: 'Gestão de Projectos com o MS project', category: 'informatica-it', imageId: 'course-ms-project' },
  { id: 'VF-86', name: 'Excel avançado', category: 'informatica-it', imageId: 'course-excel-advanced' },
  { id: 'HE-749', name: 'Marketing Digital', category: 'informatica-it', imageId: 'course-digital-marketing' },
  { id: 'JA-604', name: 'Auto Cad 3D', category: 'informatica-it', imageId: 'course-autocad' },
  { id: 'BX-274', name: 'Primavera', category: 'informatica-it', imageId: 'course-primavera' },
  { id: 'YU-738', name: 'Processamento de Salários com Primavera', category: 'informatica-it', imageId: 'course-primavera-payroll' },
  { id: 'WR-82', name: 'SAP HCM - Configuração de Processamento Salarial', category: 'informatica-it', imageId: 'course-sap-hcm' },
  { id: 'ZW-61', name: 'Excel Intermédio', category: 'informatica-it', imageId: 'course-excel-intermediate' },
  { id: 'JS-779', name: 'Excel Avançado', category: 'informatica-it', imageId: 'course-excel-advanced-2' },
  { id: 'WH-155', name: 'Excel Básico', category: 'informatica-it', imageId: 'course-excel-basic' },
  { id: 'YF-360', name: 'SAP BASIS - Melhores Práticas de Administração de Sistemas', category: 'informatica-it', imageId: 'course-sap-basis-2' },
  { id: 'NE-74', name: 'Power BI Microsoft', category: 'informatica-it', imageId: 'course-power-bi' },
  { id: 'BT-436', name: 'Administração de Redes e Infraestruturas', category: 'informatica-it', imageId: 'course-network-admin' },
  { id: 'PN-781', name: 'Segurança Informática (Sistemas e Informação)', category: 'informatica-it', imageId: 'course-infosec-2' },
  { id: 'KE-540', name: 'Microsoft Word', category: 'informatica-it', imageId: 'course-word' },
  { id: 'TY-158', name: 'Microsoft Outlook', category: 'informatica-it', imageId: 'course-outlook' },
  { id: 'WI-132', name: 'Microsoft Access', category: 'informatica-it', imageId: 'course-access' },
  { id: 'LT-654', name: 'Microsoft Teams', category: 'informatica-it', imageId: 'course-teams' },
  { id: 'CZ-730', name: 'Microsoft Office', category: 'informatica-it', imageId: 'course-office' },
  { id: 'TF-83', name: 'Primavera', category: 'informatica-it', imageId: 'course-primavera-2' },
  { id: 'IW-791', name: 'SAP-Aplicação IPL (módulo 1)', category: 'informatica-it', imageId: 'course-sap-ipl1' },
  { id: 'TQ-229', name: 'SAP-Aplicação IPL (módulo 2)', category: 'informatica-it', imageId: 'course-sap-ipl2' },
  { id: 'IP-304', name: 'Hardware', category: 'informatica-it', imageId: 'course-hardware' },
  { id: 'BA-621', name: 'Redes e Comunicações Estruturadas', category: 'informatica-it', imageId: 'course-networking' },
  { id: 'AE-78', name: 'Segurança Informática', category: 'informatica-it', imageId: 'course-infosec-3' },
  { id: 'MA-290', name: 'Excel para Finanças', category: 'informatica-it', imageId: 'course-excel-finance' },

  { id: 'ZQ-337', name: 'Alinhamento de Bombas', category: 'industrial', imageId: 'course-pump-alignment' },
  { id: 'JM-665', name: 'Inspecção e Calibração de equipamentos', category: 'industrial', imageId: 'course-calibration' },
  { id: 'OB-60', name: 'Manutenção e Reparação de Válvulas', category: 'industrial', imageId: 'course-valve-maintenance' },
  { id: 'EQ-477', name: 'Inspecção de Equipamentos', category: 'industrial', imageId: 'course-equipment-inspection' },
  { id: 'IT-121', name: 'Revestimento de Tubulações', category: 'industrial', imageId: 'course-pipe-coating' },
  { id: 'YL-705', name: 'ROV-Remotely Operated Vehicle', category: 'industrial', imageId: 'course-rov' },
  { id: 'BH-705', name: 'Montagem e Inspecção De Andaimes', category: 'industrial', imageId: 'course-scaffolding' },
  { id: 'YG-545', name: 'Operador De Empilhadora Pettibone', category: 'industrial', imageId: 'course-forklift' },
  { id: 'QE-471', name: 'Instrumentação Industrial', category: 'industrial', imageId: 'course-industrial-instrumentation' },
  { id: 'XD-764', name: 'Soldadura Industrial', category: 'industrial', imageId: 'course-welding' },
  { id: 'FV-577', name: 'Pintura Industrial', category: 'industrial', imageId: 'course-industrial-painting' },
  { id: 'GS-392', name: 'Instrumentação e Controle de Processos', category: 'industrial', imageId: 'course-process-control' },
  { id: 'GD-306', name: 'Automação Industrial', category: 'industrial', imageId: 'course-automation' },
  { id: 'UB-322', name: 'Operador de Produção', category: 'industrial', imageId: 'course-production-operator' },
  { id: 'LV-253', name: 'Operador de Sala de Controlo', category: 'industrial', imageId: 'course-control-room' },
  { id: 'LR-505', name: 'PLC - Controladores Lógicos Programáveis', category: 'industrial', imageId: 'course-plc' },
  { id: 'MU-18', name: 'Manutenção Industrial', category: 'industrial', imageId: 'course-industrial-maintenance' },
  { id: 'IJ-222', name: 'Gestão da Qualidade', category: 'industrial', imageId: 'course-quality-management-2' },
  { id: 'TG-1', name: 'Segurança Elétrica Industrial', category: 'industrial', imageId: 'course-electrical-safety' },
  { id: 'ER-426', name: 'Segurança de Processos Industriais', category: 'industrial', imageId: 'course-process-safety' },
  { id: 'KF-580', name: 'Manutenção e Reparação de Válvulas', category: 'industrial', imageId: 'course-valve-maintenance-2' },
  { id: 'LF-556', name: 'Gestão e Controle da Manutenção Industrial', category: 'industrial', imageId: 'course-maintenance-management' },
  { id: 'ER-534', name: 'Gestão por Processos e Indicadores Desempenho', category: 'industrial', imageId: 'course-process-indicators' },
  { id: 'YW-773', name: 'Gestão de Resíduos Industriais - Introdução', category: 'industrial', imageId: 'course-waste-management' },
  { id: 'AI-522', name: 'Gestão de Projectos Industriais', category: 'industrial', imageId: 'course-industrial-projects' },
  { id: 'EH-537', name: 'Gestão da Manutenção de Máquinas e Equipamentos', category: 'industrial', imageId: 'course-machine-maintenance' },

  { id: 'GR-610', name: 'Higiene e Segurança no Trabalho', category: 'seguranca-trabalho', imageId: 'course-work-safety' },
  { id: 'XX-136', name: 'Segurança Industrial e Prevenção de Riscos', category: 'seguranca-trabalho', imageId: 'course-risk-prevention' },
  { id: 'CF-669', name: 'Segurança de Máquinas – ISO 13857', category: 'seguranca-trabalho', imageId: 'course-machine-safety' },
  
  { id: 'FU-581', name: 'Técnicas de Vendas', category: 'marketing-comercial', imageId: 'course-sales-techniques' },
  { id: 'YR-504', name: 'Gestão Comercial', category: 'marketing-comercial', imageId: 'course-commercial-management' },
  { id: 'VH-377', name: 'Gestão de Clientes', category: 'marketing-comercial', imageId: 'course-client-management' },
  { id: 'RT-97', name: 'Gestão de Cobranças', category: 'marketing-comercial', imageId: 'course-debt-collection' },
  { id: 'FG-179', name: 'Técnicas de Venda', category: 'marketing-comercial', imageId: 'course-sales-techniques-2' },
  { id: 'JF-104', name: 'Técnicas de Negociação', category: 'marketing-comercial', imageId: 'course-negotiation' },
  { id: 'VP-601', name: 'Gestão da Cadeia de Suprimentos', category: 'marketing-comercial', imageId: 'course-supply-chain-2' },
  { id: 'UX-630', name: 'Gestão de Fornecedores', category: 'marketing-comercial', imageId: 'course-supplier-management' },
  { id: 'BP-642', name: 'Gestão das Reclamações', category: 'marketing-comercial', imageId: 'course-complaint-management' },
  { id: 'DH-572', name: 'Gestão de Marketing', category: 'marketing-comercial', imageId: 'course-marketing-management' },
  { id: 'TI-143', name: 'Marketing Digital', category: 'marketing-comercial', imageId: 'course-digital-marketing-2' },
  { id: 'ZY-424', name: 'ROI Marketing', category: 'marketing-comercial', imageId: 'course-roi-marketing' },
  { id: 'YL-38', name: 'Gestão Comercial', category: 'marketing-comercial', imageId: 'course-commercial-management-2' },
  { id: 'NF-265', name: 'Gestão de Clientes', category: 'marketing-comercial', imageId: 'course-client-management-2' },
  { id: 'RD-181', name: 'Gestão de Cobranças', category: 'marketing-comercial', imageId: 'course-debt-collection-2' },
  { id: 'FS-367', name: 'Técnicas de Venda', category: 'marketing-comercial', imageId: 'course-sales-techniques-3' },
  { id: 'TJ-15', name: 'Técnicas de Negociação', category: 'marketing-comercial', imageId: 'course-negotiation-2' },
  { id: 'ND-408', name: 'Gestão da Cadeia de Suprimentos', category: 'marketing-comercial', imageId: 'course-supply-chain-3' },
  { id: 'QW-537', name: 'Gestão de Fornecedores', category: 'marketing-comercial', imageId: 'course-supplier-management-2' },
  
  { id: 'YA-332', name: 'Beginner', category: 'ingles', imageId: 'course-english-beginner' },
  { id: 'NX-537', name: 'Elementary', category: 'ingles', imageId: 'course-english-elementary' },
  { id: 'ZY-640', name: 'Pre-Intermediate', category: 'ingles', imageId: 'course-english-pre-intermediate' },
  { id: 'RX-125', name: 'Intermediate', category: 'ingles', imageId: 'course-english-intermediate' },
  { id: 'JF-778', name: 'Upper Intermediate', category: 'ingles', imageId: 'course-english-upper-intermediate' },
  { id: 'WY-697', name: 'Advanced', category: 'ingles', imageId: 'course-english-advanced' },
];
